### ISSUE TITLE
Simplify version management

### ISSUE THREAD

**Issue by 00datman** [markjohndoyle/boost-nar#19]
By using a `<dependencyManagement>` block in your parent POM, you can:
1. Make it easier on yourself when you go to increment the version of this project. 
2. Make adding dependencies in submodules easier because you don't need the `<version>`
3. Make it easier on users, who can `<scope>import` your parent POM to get the same `<dependencyManagement>` for a single dependency block

I have a test build in my fork running right now, let me know if you're interested and I should be able to put up a Pull Request tomorrow.

**Comment by markjohndoyle** [comment]
Yeah, I should have set this up at the beginning, thanks! 👍
